### ISSUE TITLE
Re-organisation of folder structure.

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot-xr-template#5]
The template library currently places items in the `game` folder and `img` folder. I think this structure needs to change and be brought inline with `godot-xr-tools`.

I propose the following:

- **addons**: folder containing the addsons like XR tools itself and the OpenXR plugin/loader
- **assets**: contains models/images/sounds and other assets
- **game**: contains the levels of the game, we call this **scenes** in XR tools
  Need to make a decision which one is more apt
- **components**: what is currently **game/objects**
  These should be scenes that are used in multiple levels and/or a collection of useful commonly used items in VR.
  I suggest we move this outside of **game** so its easier to find once there are many game levels.

**Comment by Malcolmnixon** [comment]
I agree - separating out the components will help categorizing the template parts a game can optionally reuse from the game parts that should be replaced.
